
package gestionlab_i;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

public class Principal extends javax.swing.JFrame {

   
    public Principal() {
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Logo_Ingeomin_a_1.png")).getImage());
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSolicitud = new javax.swing.JLabel();
        BotonSolicitud = new javax.swing.JButton();
        BotonPersonal = new javax.swing.JButton();
        LabelPersonal = new javax.swing.JLabel();
        BotonInventario = new javax.swing.JButton();
        LabelInventario = new javax.swing.JLabel();
        BotonPresupuesto = new javax.swing.JButton();
        LabelPresupuesto = new javax.swing.JLabel();
        LabelPiePagina = new javax.swing.JLabel();
        LabelElaboradorPor = new javax.swing.JLabel();
        lblCliente_Muestra = new javax.swing.JLabel();
        botonAdministrador = new javax.swing.JButton();
        lblAdministrador = new javax.swing.JLabel();
        botonTablaPeriodica = new javax.swing.JButton();
        lblTablaPeriodica = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRINCIPAL - GENTION DE LABORATORIO -");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelSolicitud.setForeground(java.awt.Color.black);
        LabelSolicitud.setText("Solicitud");
        getContentPane().add(LabelSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        BotonSolicitud.setBackground(new java.awt.Color(192, 160, 27));
        BotonSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Solicitud_180x180.png"))); // NOI18N
        BotonSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 181, 181));

        BotonPersonal.setBackground(new java.awt.Color(192, 160, 24));
        BotonPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Personal_180x180.png"))); // NOI18N
        BotonPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 181, 181));

        LabelPersonal.setForeground(java.awt.Color.black);
        LabelPersonal.setText("Personal");
        getContentPane().add(LabelPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        BotonInventario.setBackground(new java.awt.Color(117, 126, 5));
        BotonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inventario_180x180.png"))); // NOI18N
        BotonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 181, 181));

        LabelInventario.setForeground(java.awt.Color.black);
        LabelInventario.setText("Inventario");
        getContentPane().add(LabelInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, -1, -1));

        BotonPresupuesto.setBackground(new java.awt.Color(192, 160, 24));
        BotonPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Presupuesto_180x180.png"))); // NOI18N
        BotonPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPresupuestoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 181, 181));

        LabelPresupuesto.setForeground(java.awt.Color.black);
        LabelPresupuesto.setText("Presupuesto");
        getContentPane().add(LabelPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, -1, -1));

        LabelPiePagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Diablo_a_15.png"))); // NOI18N
        getContentPane().add(LabelPiePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, -1, -1));

        LabelElaboradorPor.setForeground(java.awt.Color.black);
        LabelElaboradorPor.setText("Elaborado por: imosquerad@yahoo.com.mx");
        getContentPane().add(LabelElaboradorPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, -1));

        lblCliente_Muestra.setForeground(java.awt.Color.black);
        lblCliente_Muestra.setText("Cliente / Muestra");
        getContentPane().add(lblCliente_Muestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        botonAdministrador.setBackground(new java.awt.Color(117, 126, 5));
        botonAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Administrador.png"))); // NOI18N
        botonAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(botonAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 181, 181));

        lblAdministrador.setText("Administrador");
        getContentPane().add(lblAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        botonTablaPeriodica.setBackground(new java.awt.Color(117, 126, 5));
        botonTablaPeriodica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tablaPeriodica.png"))); // NOI18N
        botonTablaPeriodica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTablaPeriodicaActionPerformed(evt);
            }
        });
        getContentPane().add(botonTablaPeriodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 181, 181));

        lblTablaPeriodica.setText("Tabla Periodica");
        getContentPane().add(lblTablaPeriodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo_1090_698.png"))); // NOI18N
        lblFondo.setMaximumSize(new java.awt.Dimension(1082, 656));
        lblFondo.setMinimumSize(new java.awt.Dimension(1082, 656));
        lblFondo.setPreferredSize(new java.awt.Dimension(1090, 696));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSolicitudActionPerformed

         Cliente_Muestra construccion = new Cliente_Muestra();
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonSolicitudActionPerformed

    private void BotonPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPersonalActionPerformed
       Personal construccion = new Personal();
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonPersonalActionPerformed

    private void BotonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInventarioActionPerformed
        PaginaConstruccion construccion = new PaginaConstruccion();
        construccion.setBounds(0, 0, 350, 450);
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonInventarioActionPerformed

    private void BotonPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPresupuestoActionPerformed
        Presupuesto construccion = new Presupuesto();
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonPresupuestoActionPerformed

    private void botonTablaPeriodicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTablaPeriodicaActionPerformed
        TablaPeriodica construccion = new TablaPeriodica();
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_botonTablaPeriodicaActionPerformed

    private void botonAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdministradorActionPerformed
        Administrador construccion = new Administrador();
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_botonAdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       /* Principal construccion = new Principal();
        construccion.setBounds(0, 0, 1082, 656);
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);*/
        //this.setVisible(false);
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Principal().setVisible(true);
                               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInventario;
    private javax.swing.JButton BotonPersonal;
    private javax.swing.JButton BotonPresupuesto;
    private javax.swing.JButton BotonSolicitud;
    private javax.swing.JLabel LabelElaboradorPor;
    private javax.swing.JLabel LabelInventario;
    private javax.swing.JLabel LabelPersonal;
    private javax.swing.JLabel LabelPiePagina;
    private javax.swing.JLabel LabelPresupuesto;
    private javax.swing.JLabel LabelSolicitud;
    private javax.swing.JButton botonAdministrador;
    private javax.swing.JButton botonTablaPeriodica;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JLabel lblCliente_Muestra;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTablaPeriodica;
    // End of variables declaration//GEN-END:variables
}
